use mavenmovies;

-- ques1. **Rank the customers based on the total amount they've spent on rentals.**
SELECT
    c.customer_id,
    CONCAT(c.first_name, " ", c.last_name) AS full_name,
    SUM(p.amount) AS total_amount_spent,
    RANK() OVER (ORDER BY SUM(p.amount) DESC) AS customer_rank
FROM
    customer c
INNER JOIN
    payment p ON p.customer_id = c.customer_id
GROUP BY
    c.customer_id, full_name;
 
 
-- ques 2. **Calculate the cumulative revenue generated by each film over time.**

select f.film_id ,f.title, p.amount, r.rental_date, p.payment_date , sum(p.amount)  over(partition by film_id order by rental_date) as cum_rev 
from film f join inventory i on i.film_id = f.film_id join rental r on r.inventory_id = i.inventory_id
join payment p on p.rental_id = r.rental_id order by f.film_id, r.rental_date;   


-- ques 3**Determine the average rental duration for each film, considering films with similar lengths.**


select title, length, film_id, avg(rental_duration) over(partition by length) as avg_rental_dur from film;

-- 4. Identify the top 3 films in each category based on their rental counts.
SELECT 
    c.name AS category_name,
    f.title AS film_title,
    COUNT(r.rental_id) AS rental_count
FROM
    category c
        JOIN
    film_category fc ON c.category_id = fc.category_id
        JOIN
    film f ON fc.film_id = f.film_id
        LEFT JOIN
    inventory i ON f.film_id = i.film_id
        LEFT JOIN
    rental r ON i.inventory_id = r.inventory_id
GROUP BY c.category_id , f.film_id
HAVING rental_count > 0
ORDER BY c.name , rental_count DESC;




-- ques 5 **Calculate the difference in rental counts between each customer's total rentals and the average rentals across all customers.**

SELECT 
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    COUNT(r.rental_id) AS total_rentals,
    COUNT(r.rental_id) - avg_rentals.avg_rentals_all_customers AS rental_count_difference
FROM
    customer c
        LEFT JOIN
    rental r ON c.customer_id = r.customer_id
        CROSS JOIN
    (SELECT 
        AVG(sub.total_rentals) AS avg_rentals_all_customers
    FROM
        (SELECT 
        c.customer_id, COUNT(r.rental_id) AS total_rentals
    FROM
        customer c
    LEFT JOIN rental r ON c.customer_id = r.customer_id
    GROUP BY c.customer_id) sub) avg_rentals
GROUP BY c.customer_id , customer_name , avg_rentals.avg_rentals_all_customers
ORDER BY rental_count_difference DESC;
    

-- 6. Find the monthly revenue trend for the entire rental store over time.
SELECT 
    DATE_FORMAT(p.payment_date, '%Y-%m') AS payment_month,
    SUM(p.amount) AS monthly_revenue
FROM
    payment p
GROUP BY DATE_FORMAT(p.payment_date, '%Y-%m')
ORDER BY payment_month;

-- 7. Identify the customers whose total spending on rentals falls within the top 20% of all customers.
SELECT 
    customer_id,
    CONCAT(first_name, ' ', last_name) AS customer_name,
    total_amount_spent
FROM (
    SELECT 
        c.customer_id,
        c.first_name,
        c.last_name,
        SUM(p.amount) AS total_amount_spent,
        PERCENT_RANK() OVER (ORDER BY SUM(p.amount) DESC) AS pct_rank
    FROM 
        customer c
    JOIN 
        payment p ON c.customer_id = p.customer_id
    GROUP BY 
        c.customer_id
) ranked_customers
WHERE 
    pct_rank <= 0.2
ORDER BY 
    total_amount_spent DESC;

-- 8. Calculate the running total of rentals per category, ordered by rental count. 
SELECT 
    c.name AS category_name,
    f.title AS film_title,
    COUNT(r.rental_id) AS rental_count,SUM(COUNT(r.rental_id)) OVER (PARTITION BY c.name ORDER BY COUNT(r.rental_id) DESC) AS running_total_rentals
FROM 
    category c
JOIN 
    film_category fc ON c.category_id = fc.category_id
JOIN 
    film f ON fc.film_id = f.film_id
LEFT JOIN 
    inventory i ON f.film_id = i.film_id
LEFT JOIN 
    rental r ON i.inventory_id = r.inventory_id
GROUP BY 
    c.category_id, f.film_id
ORDER BY 
    rental_count DESC;

-- 9. Find the films that have been rented less than the average rental count for their respective categories.
SELECT 
    film_title,
    category_name,
    rental_count,
    avg_category_rental_count
FROM
    (SELECT 
        f.title AS film_title,
            c.name AS category_name,
            COUNT(r.rental_id) AS rental_count,
            AVG(cnt.rental_count) AS avg_category_rental_count
    FROM
        film f
    JOIN film_category fc ON f.film_id = fc.film_id
    JOIN category c ON fc.category_id = c.category_id
    LEFT JOIN (SELECT 
        f.film_id,
            fc.category_id,
            COUNT(r.rental_id) AS rental_count
    FROM
        film f
    JOIN film_category fc ON f.film_id = fc.film_id
    LEFT JOIN inventory i ON f.film_id = i.film_id
    LEFT JOIN rental r ON i.inventory_id = r.inventory_id
    GROUP BY f.film_id , fc.category_id) cnt ON f.film_id = cnt.film_id
        AND c.category_id = cnt.category_id
    LEFT JOIN inventory i ON f.film_id = i.film_id
    LEFT JOIN rental r ON i.inventory_id = r.inventory_id
    GROUP BY f.film_id , c.category_id) subquery
WHERE
    rental_count < avg_category_rental_count
ORDER BY category_name , rental_count;


-- 9th question explanation
SELECT 
    c.name AS category_name,
    AVG(cnt.rental_count) AS avg_category_rental_count
FROM
    category c
        LEFT JOIN
    (SELECT 
        fc.category_id, COUNT(r.rental_id) AS rental_count
    FROM
        film f
    JOIN film_category fc ON f.film_id = fc.film_id
    LEFT JOIN inventory i ON f.film_id = i.film_id
    LEFT JOIN rental r ON i.inventory_id = r.inventory_id
    GROUP BY fc.category_id , f.film_id) cnt ON c.category_id = cnt.category_id
GROUP BY c.category_id;

SELECT 
    f.title AS film_title,
    c.name AS category_name,
    COUNT(r.rental_id) AS rental_count
FROM
    film f
        JOIN
    film_category fc ON f.film_id = fc.film_id
        JOIN
    category c ON fc.category_id = c.category_id
        LEFT JOIN
    inventory i ON f.film_id = i.film_id
        LEFT JOIN
    rental r ON i.inventory_id = r.inventory_id
GROUP BY f.film_id , c.category_id;

-- 10)Identify the top 5 months with the highest revenue and display the revenue generated in each month.
SELECT 
    DATE_FORMAT(p.payment_date, '%Y-%m') AS payment_month,
    SUM(p.amount) AS total_revenue
FROM
    payment p
GROUP BY DATE_FORMAT(p.payment_date, '%Y-%m')
ORDER BY total_revenue DESC
LIMIT 5;

















